### ISSUE TITLE
`ssl_profile` configuration block is missing

### ISSUE THREAD

**Issue by ppawlowski** [claranet/terraform-azurerm-app-gateway#6]
Hello,

while adding your (awesome) module to my configuration stack I have noticed, that `ssl_profile` configuration block is missing (although is it supported by the azurerm provider).
When can we expect to have this functionality implemented in the module?

**Comment by Shr3ps** [comment]
Hello, 
thanks for your issue, we will look at it and try to implement it.

**Comment by Shr3ps** [comment]
Hello,

We added this feature in the latest version of the module, however we didn't manage to test deeply it.
Can you test? Don't hesitate to reopen this issue if you face any problem.

**Comment by ppawlowski** [comment]
Thanks for your great work. `ssl_profile` block looks awesome. However, there is still no possibility to attach created profile to the http listener. It should be addressed somewhere in this block: https://github.com/claranet/terraform-azurerm-app-gateway/blob/master/r-application-gateway.tf#L152
And it seems like I cannot re-open the issue @Shr3ps

**Comment by Shr3ps** [comment]
Ho yes, you're right, let's add this to http_listeners too.

**Comment by rossifumax** [comment]
Hello @ppawlowski !

Sorry for the late answer, i'll close this issue since the `ssl_profile_name` has been added to the `http_listener` block :slightly_frowning_face: 

The tag [v5.3.0](https://github.com/claranet/terraform-azurerm-app-gateway/releases/tag/v5.3.0) introduced it !
There're new tags released since this one. 

Thanks for your issue !
